version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/datapsq
    restart: always

volumes:
  pgdata: